### PR TITLE
Add recovery route to Devise email template

### PR DESCRIPTION
**Pull request by victor-nitu**

### CODE REVIEW

**Comment by georgiana-b** [comment]
@nightsh Is this still needed?

**Comment by victor-nitu** [comment]
@georgiana-b YES!

**Comment by victor-nitu** [comment]
Ping @georgiana-b

**Review by georgiana-b — APPROVED** [review]
Not too happy with this workaround but it'll do until we come up with better authentication.

**Comment by victor-nitu** [comment]
> until we come up with better authentication.

...or another backend :stuck_out_tongue_winking_eye:

**Pull request merged**
